import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Nunito, Roboto, Syne } from "next/font/google";
import "./globals.css";

import Particles from "@/components/ui/Particles";
import CustomCursor from "@/components/ui/CustomCursor";
import Home from "./components/Home/page";
import DotsNavigation from "@/components/ui/DotsNavigation";
import NavMenu from "@/components/ui/NavMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
})

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["300", "400", "500", "600", "700"],
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["300", "400", "500", "700"],
});

const numbers = Syne({
  subsets: ["latin"],
  variable: "--font-numbers",
  weight: ["500", "600", "700", "800"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`
    ${geistSans.variable}
    ${geistMono.variable}
    ${montserrat.variable}
    ${nunito.variable}
    ${roboto.variable}
    ${numbers.variable}
    antialiased
  `}
      >
        <div className="relative min-h-screen">
          <Particles className="absolute inset-0 -z-10" />
          <CustomCursor />
          <NavMenu />
          {children}

          <Home />
          <DotsNavigation />
        </div>
      </body>

    </html>
  );
}
